### ISSUE TITLE
GetGeometry returns null

### ISSUE THREAD

**Issue by aurium** [sidorares/node-x11#110]
Testing with `examples/screenshot.js`:
```
$ xwininfo | grep id
xwininfo: Window id: 0x2c0007f "How can I listen to the root events? · Issue #69"
$ node node_modules/x11/examples/screenshot.js 0x2c0007f
0x2c0007f
/tmp/node_modules/x11/examples/screenshot.js:15
        width = clientGeom.width;
                          ^
TypeError: Cannot read property 'width' of null
    at /tmp/node_modules/x11/examples/screenshot.js:15:27
...
$ node node_modules/x11/examples/screenshot.js  # try on root
undefined
/tmp/node_modules/x11/examples/screenshot.js:15
        width = clientGeom.width;
                          ^
TypeError: Cannot read property 'width' of null
    at /tmp/node_modules/x11/examples/screenshot.js:15:27
```

**Comment by sidorares** [comment]
the callback signature should be `(error, geometry)` - I suspect this example has not been updated for a long time

**Comment by sidorares** [comment]
I don't think this example is functional ( if you find time to fix actual logic feel free to submit PR!) but I pushed change anyway - 51b03c5173af6105d222e1cbfeb5b4c710bfa7ce

**Comment by sidorares** [comment]
Also if you find other outdated examples please report them. Thanks!

**Comment by aurium** [comment]
Thank! Sure, i will do, if i found!
