### ISSUE TITLE
127.0.0.1:6000  ECONNREFUSED in MAC

### ISSUE THREAD

**Issue by himanshuoodles** [sidorares/node-x11#127]
This modules is wonderful . On linux its working perfectly but on MAC OS its throwing some error when i try to `createClient`.

**Code:**

```
 var x11 = require('x11');
 x11.createClient(function(err, display) {
            if(err){ 
                  throw err;
            }
            xClient = display.client;
            xClientDisplay = display;
  });
```

**Error:**

on x11.createClient(function(err, display) { this gives an error 

[697:0525/004703:ERROR:nw_shell.cc(336)] Error: connect ECONNREFUSED 127.0.0.1:6000
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:984:14)
[697:0525/004703:INFO:CONSOLE(734)] "Uncaught Error: connect ECONNREFUSED 127.0.0.1:6000", source: util.js (734)

![screen shot 2016-05-25 at 1 39 11 am](https://cloud.githubusercontent.com/assets/15084072/15529213/94dd35f8-2219-11e6-8e16-30b1460ce106.png)

**Comment by sidorares** [comment]
Do you have X server installed in running on mac? I'm using this one - https://www.xquartz.org/

**Comment by himanshuoodles** [comment]
NO i don't have . It is necessary to install this software. I am making a desktop app in node webkit , if i install this software that means if i install my desktop app in other MAC pc i have to install this software first to run x11 command

**Comment by himanshuoodles** [comment]
![screen shot 2016-05-25 at 1 39 11 am](https://cloud.githubusercontent.com/assets/15084072/15529213/94dd35f8-2219-11e6-8e16-30b1460ce106.png)

**Comment by sidorares** [comment]
X Window system uses client/server architecture, clients connect to server ( "display server" in x11 terminology ) and server perform all visual stuff on behalf of the client. Yes, you need to have X Server running to use x11-based app. Unfortunately starting from Maverics it's not preinstalled on osx. If your target audience is mainly osx X11 is probably not the best choice

**Comment by himanshuoodles** [comment]
After installing xquartz we get this error
[691:0525/021843:ERROR:nw_shell.cc(336)] TypeError: undefined is not a function
    at readXauthority (/Users/Maneesh/Documents/productivity-front-desktopapp/node_modules/x11/lib/auth.js:56:57)
    at module.exports (/Users/Maneesh/Documents/productivity-front-desktopapp/node_modules/x11/lib/auth.js:72:3)
    at Object.writeClientHello (/Users/Maneesh/Documents/productivity-front-desktopapp/node_modules/x11/lib/handshake.js:194:5)
    at XClient.startHandshake (/Users/Maneesh/Documents/productivity-front-desktopapp/node_modules/x11/lib/xcore.js:526:15)
    at XClient.init (/Users/Maneesh/Documents/productivity-front-desktopapp/node_modules/x11/lib/xcore.js:113:10)
    at Socket.<anonymous> (/Users/Maneesh/Documents/productivity-front-desktopapp/node_modules/x11/lib/xcore.js:602:20)
    at emitNone (events.js:65:13)
    at Socket.emit (events.js:147:7)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:969:10)
[691:0525/021843:INFO:CONSOLE(56)] "Uncaught TypeError: undefined is not a function", source: /Users/Maneesh/Documents/productivity-front-desktopapp/node_modules/x11/lib/auth.js (56)

**Comment by polpo** [comment]
@himanshuoodles I am guessing you are using NW.js 0.12.x? It is based on io.js 1.2.0 which does not have the `os.homedir()` function, which the version of node-x11 that is on npm uses. A while ago a commit of mine that fixes this (582bd1a1b20d9220079bd880abcfde4ae113d24c) was merged but it is not in the node-x11 on npm yet.

You have two options: upgrade NW.js, or use node-x11 from git. (Or @sidorares can release a new x11 version to npm 😀)

**Comment by himanshuoodles** [comment]
After installation of xquatz in MAC os , I get this error.what i have done wrong


![screen shot 2016-05-25 at 2 30 19 am](https://cloud.githubusercontent.com/assets/15084072/15530162/be87371c-2220-11e6-9044-d40a39651e6b.png)



![screen shot 2016-05-25 at 2 31 34 am](https://cloud.githubusercontent.com/assets/15084072/15530181/d8fcc35a-2220-11e6-9775-273ac529d53e.png)

ERROR:nw_shell.cc(336)] TypeError: undefined is not a function
    at readXauthority (/Users/Maneesh/Documents/productivity-front-desktopapp/node_modules/x11/lib/auth.js:56:57)
    at module.exports (/Users/Maneesh/Documents/productivity-front-desktopapp/node_modules/x11/lib/auth.js:72:3)
    at Object.writeClientHello (/Users/Maneesh/Documents/productivity-front-desktopapp/node_modules/x11/lib/handshake.js:194:5)
    at XClient.startHandshake (/Users/Maneesh/Documents/productivity-front-desktopapp/node_modules/x11/lib/xcore.js:526:15)
    at XClient.init (/Users/Maneesh/Documents/productivity-front-desktopapp/node_modules/x11/lib/xcore.js:113:10)
    at Socket.<anonymous> (/Users/Maneesh/Documents/productivity-front-desktopapp/node_modules/x11/lib/xcore.js:602:20)
    at emitNone (events.js:65:13)
    at Socket.emit (events.js:147:7)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:969:10)
[740:0525/022808:INFO:CONSOLE(56)] "Uncaught TypeError: undefined is not a function", source: /Users/Maneesh/Documents/productivity-front-desktopapp/node_modules/x11/lib/auth.js (56)

**Comment by polpo** [comment]
@himanshuoodles try replacing the x11 package installed from npm with the master branch on GitHub: `npm i --save sidorares/node-x11`

**Comment by sidorares** [comment]
@polpo v2.1.0 :)

**Comment by sidorares** [comment]
```
node-x11 (master) $ npm owner add polpo x11
+ polpo (x11)
```

@polpo if you don't mind :)

**Comment by polpo** [comment]
@sidorares excellent, thanks!

**Comment by polpo** [comment]
@himanshuoodles you can just upgrade node-x11 now by doing `npm i --save x11`

**Comment by himanshuoodles** [comment]
thanks @polpo  @sidorares for your time . yes this work for me

**Comment by sidorares** [comment]
@himanshuoodles  feel free to reopen if there are more connection-related questions or create new issue if you need help on a different topic
