### ISSUE TITLE
Can only use black and white colors

### ISSUE THREAD

**Issue by SpaceboyRoss01** [sidorares/node-x11#144]
Why can't I render any colors that are not black and white.
I get this error:
```
Error
    at XClient.req_proxy [as ChangeGC] (/home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/x11/lib/xcore.js:189:30)
    at RenderingContextX11.RC.setBackground (/home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/ntk/lib/renderingcontext_x11.js:31:17)
    at new WindowManager (/home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/wm/index.js:19:29)
    at /home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/index.js:6:2
    at callback (/home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/ntk/lib/index.js:17:17)
    at /home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/ntk/lib/index.js:56:13
    at /home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/x11/lib/xcore.js:590:8
    at /home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/x11/lib/ext/render.js:607:17
    at ReadFixedRequest.callback (/home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/x11/lib/xcore.js:545:21)
    at ReadFixedRequest.execute (/home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/x11/lib/unpackstream.js:41:10)
{ Error
    at XClient.req_proxy [as ChangeGC] (/home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/x11/lib/xcore.js:189:30)
    at RenderingContextX11.RC.setBackground (/home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/ntk/lib/renderingcontext_x11.js:31:17)
    at new WindowManager (/home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/wm/index.js:19:29)
    at /home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/index.js:6:2
    at callback (/home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/ntk/lib/index.js:17:17)
    at /home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/ntk/lib/index.js:56:13
    at /home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/x11/lib/xcore.js:590:8
    at /home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/x11/lib/ext/render.js:607:17
    at ReadFixedRequest.callback (/home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/x11/lib/xcore.js:545:21)
    at ReadFixedRequest.execute (/home/spaceboyross/Documents/entertaingmentOS-core/src/GUI/node_modules/x11/lib/unpackstream.js:41:10) timestamp: 1495388246048 }

```

**Comment by sidorares** [comment]
can I look at the code? I guess it's https://github.com/Ross-Computers/entertaingmentOS-core but nothing pushed yet?

if you are using ntk I suggest to use Render-based `2d` context instead of `x11` context ( which is based on 30+ years old  core X11 drawing api )

**Comment by SpaceboyRoss01** [comment]
My code is lost just now from AMD Radeon drivers failing to run

**Comment by sidorares** [comment]
Closing — no reproduction and the original code was lost. The core drawing and Render paths have since been rewritten and are covered by tests (#215/#216/#217); if you hit this again on a current version please open a fresh issue with a snippet.
