### ISSUE TITLE
Cannot set _MOTIF_WM_HINTS

### ISSUE THREAD

**Issue by SpaceboyRoss01** [sidorares/node-x11#178]
This code appears to not work, I tried using `x11-prop` but it says that "Unsupported type: _MOTIF_WM_HINTS."
```js
X.InternAtom(false,"_MOTIF_WM_HINTS",(err,_MOTIF_WM_HINTS) => {
    if(err) throw err;
    X.ChangeProperty(0,wid,_MOTIF_WM_HINTS,_MOTIF_WM_HINTS,32,[0x2,0x0,0x0,0x0,0x0]);
});
```

Exception:
```
/home/spaceboyross/RDE-panel/node_modules/x11/lib/unpackstream.js:281
                        buf[offset++] = str.charCodeAt(c);
                                            ^

TypeError: str.charCodeAt is not a function
    at UnpackStream.pack (/home/spaceboyross/RDE-panel/node_modules/x11/lib/unpackstream.js:281:45)
    at XClient.req_proxy [as ChangeProperty] (/home/spaceboyross/RDE-panel/node_modules/x11/lib/xcore.js:229:37)
    at app.getXClient.InternAtom (/home/spaceboyross/RDE-panel/panel.js:61:28)
    at ReadFixedRequest.callback (/home/spaceboyross/RDE-panel/node_modules/x11/lib/xcore.js:545:21)
    at ReadFixedRequest.execute (/home/spaceboyross/RDE-panel/node_modules/x11/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/home/spaceboyross/RDE-panel/node_modules/x11/lib/unpackstream.js:165:30)
    at UnpackStream.write (/home/spaceboyross/RDE-panel/node_modules/x11/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/home/spaceboyross/RDE-panel/node_modules/x11/lib/xcore.js:88:21)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
```

**Comment by SpaceboyRoss01** [comment]
I have this fixed in a pull request https://github.com/sidorares/node-x11/pull/181
