### ISSUE TITLE
Error in glxgears

### ISSUE THREAD

**Issue by arteze** [sidorares/node-x11#203]
I obtain this error at execute `examples/opengl/glxgears.js`.

```js
node
Welcome to Node.js v16.3.0.
Type ".help" for more information.
> x=require("/x11njs/examples/opengl/glxgears.js")
{}
> 887

64
Error: Bad param value
    at ReadFixedRequest.callback (/x11njs/lib/xcore.js:472:29)
    at ReadFixedRequest.execute (/x11njs/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/x11njs/lib/unpackstream.js:165:30)
    at UnpackStream.write (/x11njs/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/x11njs/lib/xcore.js:88:21)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:532:15)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10) {
  error: 2,
  seq: 7,
  badParam: 0,
  minorOpcode: 3,
  majorOpcode: 150
}
Error: GLX: Bad context
    at ReadFixedRequest.callback (/x11njs/lib/xcore.js:472:29)
    at ReadFixedRequest.execute (/x11njs/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/x11njs/lib/unpackstream.js:165:30)
    at UnpackStream.write (/x11njs/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/x11njs/lib/xcore.js:88:21)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:532:15)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10) {
  error: 156,
  seq: 8,
  badParam: 0,
  minorOpcode: 5,
  majorOpcode: 150
}
Error: GLX: Bad context tag
    at ReadFixedRequest.callback (/x11njs/lib/xcore.js:472:29)
    at ReadFixedRequest.execute (/x11njs/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/x11njs/lib/unpackstream.js:165:30)
    at UnpackStream.write (/x11njs/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/x11njs/lib/xcore.js:88:21)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:532:15)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10) {
  error: 160,
  seq: 9,
  badParam: 35651587,
  minorOpcode: 1,
  majorOpcode: 150
}
Error: GLX: Bad context tag
    at ReadFixedRequest.callback (/x11njs/lib/xcore.js:472:29)
    at ReadFixedRequest.execute (/x11njs/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/x11njs/lib/unpackstream.js:165:30)
    at UnpackStream.write (/x11njs/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/x11njs/lib/xcore.js:88:21)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:532:15)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10) {
  error: 160,
  seq: 10,
  badParam: 35651587,
  minorOpcode: 104,
  majorOpcode: 150
}
Error: GLX: Bad context tag
    at ReadFixedRequest.callback (/x11njs/lib/xcore.js:472:29)
    at ReadFixedRequest.execute (/x11njs/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/x11njs/lib/unpackstream.js:165:30)
    at UnpackStream.write (/x11njs/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/x11njs/lib/xcore.js:88:21)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:532:15)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10) {
  error: 160,
  seq: 10,
  badParam: 35651587,
  minorOpcode: 104,
  majorOpcode: 150
}

```

**Comment by sidorares** [comment]
Root cause: your X server has indirect GLX disabled (the default on all modern servers), so `glXCreateContext` over the wire fails. node-x11 talks the GLX *protocol* — it can only ever create indirect contexts, so the server must be started with `+iglx` (Xorg: also `Option "AllowIndirectGLX" "on"`; details per server in [docs/ext/glx.md](https://github.com/sidorares/node-x11/blob/master/docs/ext/glx.md#server-setup-indirect-glx-must-be-enabled)).

Since then the whole GLX layer was rewritten (#218) — glxgears and a set of new examples work against any server with `+iglx` enabled. Closing; if it still fails for you on current master with `+iglx` verified via `pgrep -fl X`, please open a fresh issue.
