### ISSUE TITLE
Rare exception handling GetProperty reply

### ISSUE THREAD

**Issue by santigimeno** [sidorares/node-x11#35]
Very rarely I'm receiving this exception:

Error: oob
at Buffer.slice (buffer.js:558:32)
at XClient.module.exports.GetProperty (/usr/share/smartion-node/node_modules/x11/lib/corereqs.js:409:28)
at ReadFixedRequest.XClient.expectReplyHeader [as callback](/usr/share/smartion-node/node_modules/x11/lib/xcore.js:439:41)
at ReadFixedRequest.execute (/usr/share/smartion-node/node_modules/x11/lib/unpackstream.js:41:10)
at UnpackStream.resume (/usr/share/smartion-node/node_modules/x11/lib/unpackstream.js:165:30)
at UnpackStream.write (/usr/share/smartion-node/node_modules/x11/lib/unpackstream.js:102:10)
at Socket.<anonymous> (/usr/share/smartion-node/node_modules/x11/lib/xcore.js:57:21)
at Socket.EventEmitter.emit (events.js:96:17)
at Pipe.onread (net.js:397:14)

I don't find anything wrong in the code. Of course, I'll keep investigating, but is there anything in the code that draws your attention that could be causing this? 

Thanks!

@sidorares

**Comment by sidorares** [comment]
The unpack layer in this stack trace (`pack_stream.get` + format-string parsing) was completely replaced with bounds-checked Buffer reads and XML-generated reply parsers in #215, so this 2013 code path no longer exists. Closing; please open a fresh issue if anything similar shows up on current master.
